const QUESTIONS = [
  {
    id: "l1-oc-mcq",
    type: "multiple-choice",
    topic: "Economic foundations",
    source: "Lecture 1",
    title: "Opportunity cost",
    prompt: "What is the opportunity cost of choosing an action?",
    options: [
      "The money price paid for the action",
      "The value of the next best alternative sacrificed",
      "Every possible benefit that was not chosen",
      "The accounting cost plus tax",
    ],
    answer: 1,
    explanation: "Opportunity cost is the value of the next best alternative forgone when a choice is made.",
  },
  {
    id: "l1-positive-normative",
    type: "short-answer",
    topic: "Economic foundations",
    source: "Lecture 1",
    title: "Positive or normative",
    prompt: "Explain the difference between positive and normative economic statements.",
    rubric: [
      { label: "Positive statements describe what is or make testable claims.", points: 1, keywords: [["positive", "test"], ["positive", "verifiable"], ["what is"]] },
      { label: "Normative statements describe what ought to be or express value judgements.", points: 1, keywords: [["normative", "ought"], ["should"], ["value", "judgement"]] },
      { label: "Mentions that positive claims can be checked against evidence.", points: 1, keywords: [["evidence"], ["facts"], ["proven"], ["verified"]] },
    ],
    modelAnswer: "Positive analysis concerns testable claims about what is happening, while normative analysis concerns what ought to happen and depends on opinions or values. Positive claims can in principle be checked against evidence.",
  },
  {
    id: "l2-ppf-mcq",
    type: "multiple-choice",
    topic: "PPF and trade",
    source: "Lecture 2",
    title: "Inside the PPF",
    prompt: "A point inside a production possibility frontier is best described as:",
    options: [
      "Unattainable with current resources",
      "Attainable but inefficient",
      "Efficient and unattainable",
      "A point where opportunity cost is zero",
    ],
    answer: 1,
    explanation: "A point inside the PPF is attainable, but it does not use available resources fully or efficiently.",
  },
  {
    id: "l2-comparative-advantage",
    type: "short-answer",
    topic: "PPF and trade",
    source: "Lecture 2",
    title: "Comparative advantage",
    prompt: "What determines comparative advantage, and why does it create gains from trade?",
    rubric: [
      { label: "Defines comparative advantage using lower opportunity cost.", points: 2, keywords: [["lower", "opportunity", "cost"], ["comparative", "opportunity"]] },
      { label: "Explains specialisation according to comparative advantage.", points: 1, keywords: [["specialise"], ["specialization"]] },
      { label: "Explains that trade can allow consumption beyond individual production possibilities.", points: 1, keywords: [["trade", "better"], ["beyond", "ppf"], ["gains", "trade"]] },
    ],
    modelAnswer: "Comparative advantage is determined by lower opportunity cost, not absolute productivity. If each party specialises in the good it produces at lower opportunity cost and then trades, both can potentially consume more than they could alone.",
  },
  {
    id: "l3-demand-shift-mcq",
    type: "multiple-choice",
    topic: "Demand and supply",
    source: "Lecture 3",
    title: "Demand shift",
    prompt: "If the price of a substitute good rises, what usually happens to demand for the original good?",
    options: ["Demand decreases", "Demand increases", "Quantity demanded falls only", "Supply increases"],
    answer: 1,
    explanation: "A higher price for a substitute makes the original good relatively more attractive, shifting its demand curve to the right.",
  },
  {
    id: "l3-equilibrium-short",
    type: "short-answer",
    topic: "Demand and supply",
    source: "Lecture 3",
    title: "Market equilibrium",
    prompt: "Define market equilibrium and describe what happens if price is above equilibrium.",
    rubric: [
      { label: "Defines equilibrium as the point where demand and supply meet, or where quantity demanded equals quantity supplied.", points: 2, concepts: ["equilibriumDefinition"] },
      { label: "Identifies surplus or excess supply when price is above equilibrium.", points: 1, concepts: ["excessSupply"] },
      { label: "Explains downward pressure on price.", points: 1, concepts: ["downwardPricePressure"] },
    ],
    modelAnswer: "Market equilibrium occurs where quantity demanded equals quantity supplied. If price is above equilibrium there is excess supply, so sellers have an incentive to lower price until the surplus disappears.",
  },
  {
    id: "l3-graph-demand-increase",
    type: "graph",
    topic: "Demand and supply",
    source: "Lecture 3",
    title: "Increase in demand",
    graphMode: "complete",
    template: "demandSupplyBase",
    prompt: "Complete the graph by drawing the new demand curve after an increase in demand and marking the new equilibrium.",
    checks: [
      { label: "New demand curve shifts right.", points: 2 },
      { label: "New demand curve remains downward sloping and roughly parallel to D1.", points: 1 },
      { label: "New equilibrium is marked where D2 intersects S.", points: 2 },
      { label: "New equilibrium has higher price and higher quantity.", points: 2 },
    ],
    modelAnswer: "The correct graph has P on the vertical axis and Q on the horizontal axis. Supply slopes upward, demand slopes downward, demand shifts right, and the new intersection is at a higher price and higher quantity.",
  },
  {
    id: "l4-ped-calc",
    type: "short-answer",
    topic: "Elasticity and policy",
    source: "Lecture 4",
    title: "Elasticity calculation",
    prompt: "A price rise of 20% causes quantity demanded to fall by 10%. Calculate PED and classify demand.",
    rubric: [
      { label: "Uses percentage change in quantity divided by percentage change in price.", points: 1, keywords: [["10", "20"], ["quantity", "price"]] },
      { label: "Calculates elasticity magnitude as 0.5.", points: 2, keywords: [["0.5"], ["-0.5"]] },
      { label: "Classifies demand as inelastic.", points: 1, keywords: [["inelastic"]] },
    ],
    modelAnswer: "PED = -10% / 20% = -0.5. In absolute value this is 0.5, so demand is price inelastic.",
  },
  {
    id: "l4-tax-incidence-mcq",
    type: "multiple-choice",
    topic: "Elasticity and policy",
    source: "Lecture 4",
    title: "Tax incidence",
    prompt: "When demand is relatively inelastic and supply is relatively elastic, who bears more of a per-unit tax?",
    options: ["Consumers", "Producers", "The government", "No one, because tax incidence disappears"],
    answer: 0,
    explanation: "The less elastic side of the market bears more of the tax burden. If demand is relatively inelastic, consumers bear more.",
  },
  {
    id: "l4-price-ceiling-graph",
    type: "graph",
    topic: "Elasticity and policy",
    source: "Lecture 4",
    title: "Binding price ceiling",
    graphMode: "choice",
    prompt: "Choose the graph that correctly shows a binding price ceiling and the resulting shortage.",
    options: [
      { label: "A. Ceiling below equilibrium with shortage", diagram: "priceCeilingCorrect" },
      { label: "B. Ceiling above equilibrium", diagram: "priceCeilingTooHigh" },
      { label: "C. Price floor above equilibrium with surplus", diagram: "priceFloorWrong" },
    ],
    answer: 0,
    modelAnswer: "A binding price ceiling is below the equilibrium price. At that legal maximum price, quantity demanded is greater than quantity supplied, so the market has a shortage.",
  },
  {
    id: "l5-mrs-mcq",
    type: "multiple-choice",
    topic: "Consumer choice",
    source: "Lecture 5",
    title: "MRS",
    prompt: "The marginal rate of substitution measures:",
    options: [
      "The price of one good divided by income",
      "The rate at which a consumer is willing to trade one good for another while keeping utility constant",
      "The rate at which firms substitute capital for labour",
      "The difference between total utility and marginal utility",
    ],
    answer: 1,
    explanation: "MRS is the slope of the indifference curve and shows the tradeoff the consumer is willing to make while staying on the same utility level.",
  },
  {
    id: "l5-consumer-equilibrium",
    type: "short-answer",
    topic: "Consumer choice",
    source: "Lecture 5",
    title: "Consumer equilibrium",
    prompt: "State the consumer equilibrium condition using indifference curves and a budget line.",
    rubric: [
      { label: "Mentions the best affordable bundle.", points: 1, keywords: [["best", "affordable"], ["utility", "max"]] },
      { label: "States tangency between indifference curve and budget line.", points: 1, keywords: [["tangent"], ["tangency"]] },
      { label: "States MRS equals relative price or slope of budget line.", points: 2, keywords: [["mrs", "relative", "price"], ["mrs", "slope"], ["mrs", "px", "py"]] },
    ],
    modelAnswer: "The consumer chooses the best affordable bundle on the budget line. At an interior optimum, the indifference curve is tangent to the budget line, so MRS equals the relative price ratio.",
  },
  {
    id: "l6-economic-profit",
    type: "short-answer",
    topic: "Production and costs",
    source: "Lecture 6",
    title: "Economic profit",
    prompt: "Why can a firm earn positive accounting profit but zero economic profit?",
    rubric: [
      { label: "Distinguishes accounting costs from economic costs.", points: 1, keywords: [["accounting", "economic"]] },
      { label: "Mentions implicit or opportunity costs.", points: 2, keywords: [["implicit"], ["opportunity", "cost"]] },
      { label: "Explains zero economic profit as normal profit.", points: 1, keywords: [["normal", "profit"], ["zero", "economic"]] },
    ],
    modelAnswer: "Economic cost includes accounting costs plus implicit opportunity costs such as the owner's time or capital. A firm may cover explicit costs and show accounting profit, while just covering all economic costs, which is zero economic profit or normal profit.",
  },
  {
    id: "l6-diminishing-returns-mcq",
    type: "multiple-choice",
    topic: "Production and costs",
    source: "Lecture 6",
    title: "Diminishing marginal returns",
    prompt: "The law of diminishing marginal returns applies when:",
    options: [
      "All inputs are variable in the long run",
      "More of a variable input is added to fixed inputs and marginal product eventually falls",
      "Average cost is always falling",
      "Output falls whenever labour increases",
    ],
    answer: 1,
    explanation: "In the short run, at least one input is fixed. Adding more of a variable input eventually causes marginal product to decline.",
  },
  {
    id: "l6-cost-curves-graph",
    type: "graph",
    topic: "Production and costs",
    source: "Lecture 6",
    title: "MC and average cost",
    graphMode: "choice",
    prompt: "Choose the graph that correctly shows the relationship between MC, AVC and ATC.",
    options: [
      { label: "A. ATC above AVC; MC crosses both at their minimums", diagram: "costCurvesCorrect" },
      { label: "B. ATC below AVC", diagram: "costCurvesWrongAtcBelow" },
      { label: "C. Demand shift graph", diagram: "demandIncreaseCorrect" },
    ],
    answer: 0,
    modelAnswer: "AVC and ATC are U-shaped, with ATC above AVC because it includes AFC. MC intersects AVC and ATC at their minimum points; when MC is below an average, the average falls, and when MC is above it, the average rises.",
  },
  {
    id: "l7-dominant-strategy",
    type: "short-answer",
    topic: "Game theory",
    source: "Lecture 7",
    title: "Dominant strategy",
    prompt: "What is a dominant strategy, and how is it different from a Nash equilibrium?",
    rubric: [
      { label: "Defines dominant strategy as best regardless of rival action.", points: 2, keywords: [["regardless"], ["no matter"], ["whatever", "other"]] },
      { label: "Defines Nash equilibrium as mutual best responses.", points: 2, keywords: [["best", "response"], ["no", "incentive", "deviate"], ["nash"]] },
      { label: "Explains a Nash equilibrium need not involve dominant strategies.", points: 1, keywords: [["not", "dominant"], ["need not"], ["may not"]] },
    ],
    modelAnswer: "A dominant strategy is a player's best strategy no matter what the other player does. A Nash equilibrium is a set of strategies where each player is choosing a best response to the other, so no one wants to deviate. Nash equilibria can exist without dominant strategies.",
  },
  {
    id: "l7-prisoners-mcq",
    type: "multiple-choice",
    topic: "Game theory",
    source: "Lecture 7",
    title: "Prisoner's dilemma",
    prompt: "The key lesson of the prisoner's dilemma is that:",
    options: [
      "Individual incentives can lead to a worse collective outcome",
      "Cooperation is always a dominant strategy",
      "There are no Nash equilibria",
      "Repeated interaction always eliminates cheating",
    ],
    answer: 0,
    explanation: "In a prisoner's dilemma, individually rational choices can produce an outcome that is worse for the group than cooperation.",
  },
  {
    id: "l8-perfect-competition-profit",
    type: "short-answer",
    topic: "Perfect competition",
    source: "Lecture 8",
    title: "Profit maximisation",
    prompt: "For a perfectly competitive firm, why is the profit-maximising rule P = MC?",
    rubric: [
      { label: "Identifies the firm as a price taker.", points: 1, keywords: [["price", "taker"]] },
      { label: "States that MR equals price.", points: 2, keywords: [["mr", "p"], ["marginal revenue", "price"]] },
      { label: "Uses the general rule MR = MC.", points: 1, keywords: [["mr", "mc"], ["marginal revenue", "marginal cost"]] },
    ],
    modelAnswer: "A perfectly competitive firm is a price taker, so each extra unit sold adds revenue equal to the market price. Since profit is maximised where MR = MC and MR = P, the rule becomes P = MC.",
  },
  {
    id: "l8-shutdown-mcq",
    type: "multiple-choice",
    topic: "Perfect competition",
    source: "Lecture 8",
    title: "Shutdown rule",
    prompt: "In the short run, a competitive firm should shut down if:",
    options: ["P is below minimum AVC", "P is below minimum ATC", "P equals MC", "Economic profit is zero"],
    answer: 0,
    explanation: "A firm shuts down in the short run when price is below minimum average variable cost, because it cannot cover variable costs.",
  },
  {
    id: "l8-welfare-graph",
    type: "graph",
    topic: "Perfect competition",
    source: "Lecture 8",
    title: "Competitive welfare",
    graphMode: "choice",
    prompt: "Choose the graph that correctly identifies consumer surplus and producer surplus at competitive equilibrium.",
    options: [
      { label: "A. CS above price and PS below price", diagram: "welfareCorrect" },
      { label: "B. Price ceiling graph", diagram: "priceCeilingCorrect" },
      { label: "C. Monopoly MR graph", diagram: "monopolyCorrect" },
    ],
    answer: 0,
    modelAnswer: "The efficient competitive equilibrium is where demand/MB intersects supply/MC. Consumer surplus is the area under demand and above price; producer surplus is above supply and below price. Their sum is social surplus.",
  },
  {
    id: "l9-monopoly-mr",
    type: "short-answer",
    topic: "Monopoly",
    source: "Lecture 9",
    title: "Monopoly MR",
    prompt: "Why is marginal revenue below price for a single-price monopolist?",
    rubric: [
      { label: "Monopolist faces the market demand curve.", points: 1, keywords: [["market", "demand"], ["downward", "demand"]] },
      { label: "Must lower price to sell additional units.", points: 2, keywords: [["lower", "price"], ["reduce", "price"]] },
      { label: "Extra revenue from new unit is partly offset by lower price on previous units.", points: 2, keywords: [["previous"], ["all units"], ["offset"], ["lost", "revenue"]] },
    ],
    modelAnswer: "A monopolist faces the downward-sloping market demand curve, so selling more requires lowering price. The revenue from the extra unit is partly offset by the lower price received on units that could already have been sold, so MR is below price.",
  },
  {
    id: "l9-monopoly-graph",
    type: "graph",
    topic: "Monopoly",
    source: "Lecture 9",
    title: "Monopoly output and price",
    graphMode: "choice",
    prompt: "Choose the graph structure a monopolist uses to find profit-maximising output and price.",
    options: [
      { label: "A. Demand with MR below it and MC crossing MR", diagram: "monopolyCorrect" },
      { label: "B. Competitive welfare graph", diagram: "welfareCorrect" },
      { label: "C. Demand increase graph", diagram: "demandIncreaseCorrect" },
    ],
    answer: 0,
    modelAnswer: "A monopolist chooses Q where MR = MC, then moves up to the demand curve to set price. Because demand is above MR, the monopoly price is above marginal cost at the chosen quantity.",
  },
  {
    id: "l9-natural-monopoly-mcq",
    type: "multiple-choice",
    topic: "Monopoly",
    source: "Lecture 9",
    title: "Natural monopoly",
    prompt: "A natural monopoly exists when:",
    options: [
      "The government bans entry for all firms",
      "One firm can supply the market at lower average cost than multiple firms",
      "The product has perfect substitutes",
      "Marginal revenue equals price",
    ],
    answer: 1,
    explanation: "Natural monopoly arises when economies of scale mean one firm can serve the whole market at lower average cost than two or more firms.",
  },
  {
    id: "l10-hhi",
    type: "short-answer",
    topic: "Imperfect competition",
    source: "Lecture 10",
    title: "HHI",
    prompt: "Calculate the HHI for a market with four firms holding 30%, 30%, 20% and 20% shares.",
    rubric: [
      { label: "Squares each firm's market share.", points: 1, keywords: [["30", "30"], ["20", "20"], ["squared"]] },
      { label: "Adds the squared shares.", points: 1, keywords: [["add"], ["sum"], ["+"] ] },
      { label: "Reports HHI as 2600.", points: 2, keywords: [["2600"], ["2,600"]] },
    ],
    modelAnswer: "HHI = 30^2 + 30^2 + 20^2 + 20^2 = 900 + 900 + 400 + 400 = 2600.",
  },
  {
    id: "l10-monop-comp-long",
    type: "long-answer",
    topic: "Imperfect competition",
    source: "Lecture 10",
    title: "Monopolistic competition",
    prompt: "Explain the short-run and long-run outcome for a monopolistically competitive firm earning supernormal profit.",
    rubric: [
      { label: "Notes product differentiation and downward-sloping firm demand.", points: 1, keywords: [["differentiated"], ["downward", "demand"]] },
      { label: "States short-run profit maximisation at MR = MC.", points: 1, keywords: [["mr", "mc"]] },
      { label: "Identifies supernormal profit when price exceeds average cost.", points: 1, keywords: [["p", "ac"], ["price", "average cost"], ["supernormal"]] },
      { label: "Explains entry due to no barriers or free entry.", points: 2, keywords: [["entry"], ["new firms"], ["no barriers"], ["free entry"]] },
      { label: "Explains demand for each existing firm shifts left until normal profit.", points: 2, keywords: [["demand", "left"], ["normal", "profit"], ["p", "ac"]] },
      { label: "Mentions excess capacity or price above minimum average cost in long run.", points: 1, keywords: [["excess capacity"], ["minimum average cost"], ["min ac"]] },
    ],
    modelAnswer: "In monopolistic competition, firms sell differentiated products and face downward-sloping demand. In the short run a firm maximises profit where MR = MC and can earn supernormal profit if P > AC. Because entry is free, those profits attract new firms. Close substitutes increase, so each existing firm's demand and MR shift left until P = AC and only normal profit remains. Unlike perfect competition, the long-run outcome is not at minimum average cost, so there is excess capacity.",
  },
  {
    id: "l10-cartel-mcq",
    type: "multiple-choice",
    topic: "Imperfect competition",
    source: "Lecture 10",
    title: "Cartel instability",
    prompt: "Why are cartels often unstable?",
    options: [
      "Each firm has an incentive to cheat by producing more or cutting price",
      "Cartels always have free entry",
      "Marginal cost is always zero",
      "Demand is perfectly elastic for every cartel firm",
    ],
    answer: 0,
    explanation: "Even if firms collectively benefit from restricting output, each firm can often gain in the short run by cheating on the agreement.",
  },
  {
    id: "l11-negative-externality",
    type: "short-answer",
    topic: "Externalities",
    source: "Lecture 11",
    title: "Negative externality",
    prompt: "Why does a competitive market overproduce a good with a negative production externality?",
    rubric: [
      { label: "Identifies external cost imposed on third parties.", points: 1, keywords: [["external", "cost"], ["third party"]] },
      { label: "Distinguishes private cost from social cost.", points: 2, keywords: [["private", "social"], ["social cost"]] },
      { label: "Explains firms consider private cost, not full social cost.", points: 1, keywords: [["private cost"], ["ignore"], ["not consider"]] },
      { label: "Concludes market output exceeds efficient output.", points: 2, keywords: [["overproduce"], ["too much"], ["exceeds", "efficient"], ["higher", "efficient"]] },
    ],
    modelAnswer: "With a negative production externality, production imposes costs on third parties. Firms base output on private cost, but social cost is private cost plus external cost. Because the market ignores part of the cost, the private equilibrium quantity is greater than the efficient quantity.",
  },
  {
    id: "l11-externality-graph",
    type: "graph",
    topic: "Externalities",
    source: "Lecture 11",
    title: "Negative production externality",
    graphMode: "complete",
    template: "negativeExternalityBase",
    prompt: "Complete the graph by adding the social cost curve for a negative production externality and marking the efficient quantity.",
    checks: [
      { label: "Social cost curve lies above private cost.", points: 2 },
      { label: "Social cost curve slopes upward.", points: 1 },
      { label: "Efficient quantity is where demand intersects social cost.", points: 2 },
      { label: "Market quantity is greater than efficient quantity.", points: 2 },
    ],
    modelAnswer: "The social cost curve sits above the private cost/supply curve. The market chooses the quantity where demand equals private cost, while the efficient quantity is where demand equals social cost. Therefore the market quantity is too high.",
  },
  {
    id: "l11-coase",
    type: "long-answer",
    topic: "Externalities",
    source: "Lecture 11",
    title: "Coase theorem",
    prompt: "Explain the Coase theorem and the role of transaction costs and property rights.",
    rubric: [
      { label: "States that bargaining can reach an efficient outcome.", points: 2, keywords: [["bargaining", "efficient"], ["negotiate", "efficient"]] },
      { label: "Requires well-defined property rights.", points: 2, keywords: [["property rights"], ["right"]] },
      { label: "Requires low or zero transaction costs.", points: 2, keywords: [["transaction cost"], ["low cost"], ["zero cost"]] },
      { label: "Notes allocation of rights affects distribution, not efficiency, under ideal conditions.", points: 1, keywords: [["distribution"], ["who pays"], ["allocation"]] },
      { label: "Explains high transaction costs or many parties can prevent bargaining.", points: 1, keywords: [["many parties"], ["high transaction"], ["bargaining fails"]] },
    ],
    modelAnswer: "The Coase theorem says that if property rights are clearly defined and transaction costs are low, affected parties can bargain to reach the efficient outcome regardless of who initially holds the right. The initial right affects who pays whom, so it matters for distribution. With many parties or high transaction costs, bargaining may fail and policy intervention may be needed.",
  },
  {
    id: "l12-goods-mcq",
    type: "multiple-choice",
    topic: "Public goods",
    source: "Lecture 12",
    title: "Public goods",
    prompt: "A pure public good is:",
    options: [
      "Rival and excludable",
      "Non-rival and non-excludable",
      "Rival and non-excludable",
      "Non-rival and excludable",
    ],
    answer: 1,
    explanation: "A pure public good is non-rival in consumption and non-excludable.",
  },
  {
    id: "l12-free-rider",
    type: "short-answer",
    topic: "Public goods",
    source: "Lecture 12",
    title: "Free riding",
    prompt: "Why does the free-rider problem lead to under-provision of public goods?",
    rubric: [
      { label: "Identifies non-excludability.", points: 1, keywords: [["non-excludable"], ["cannot exclude"], ["hard to exclude"]] },
      { label: "Explains individuals can benefit without paying.", points: 2, keywords: [["without paying"], ["free ride"], ["benefit", "pay"]] },
      { label: "Explains people understate willingness to pay or avoid contribution.", points: 1, keywords: [["willingness to pay"], ["contribution"], ["reveal"]] },
      { label: "Concludes private market provides too little or none.", points: 2, keywords: [["under-provision"], ["too little"], ["not produced"], ["zero"]] },
    ],
    modelAnswer: "Because public goods are non-excludable, people can consume them even if they do not pay. Each person has an incentive to understate their willingness to pay and rely on others to contribute, so private provision tends to be too low or absent.",
  },
  {
    id: "l12-tragedy-long",
    type: "long-answer",
    topic: "Public goods",
    source: "Lecture 12",
    title: "Tragedy of the commons",
    prompt: "Explain the tragedy of the commons using overfishing as an example.",
    rubric: [
      { label: "Defines common resources as rival and non-excludable.", points: 2, keywords: [["rival", "non-excludable"], ["common resource"]] },
      { label: "Applies the idea to fish stocks or open-access fishing.", points: 1, keywords: [["fish"], ["overfishing"], ["open access"]] },
      { label: "Explains individual users ignore the external cost imposed on others.", points: 2, keywords: [["external cost"], ["others"], ["ignore"], ["stock"]] },
      { label: "Shows private incentives lead to excessive use.", points: 2, keywords: [["too much"], ["overuse"], ["excessive"], ["overfish"]] },
      { label: "Mentions a possible solution such as property rights, quotas, regulation or taxes.", points: 1, keywords: [["property rights"], ["quota"], ["regulation"], ["tax"]] },
    ],
    modelAnswer: "Common resources are rival but hard to exclude people from using. In an open-access fishery, each fisher gains from catching more fish but does not fully bear the cost of reducing the stock for others. Individual incentives therefore push total fishing effort above the efficient level. Solutions can include property rights, quotas, licences, regulation or taxes.",
  },
  {
    id: "mix-welfare-tax-long",
    type: "long-answer",
    topic: "Elasticity and policy",
    source: "Lectures 4 and 8",
    title: "Tax welfare effects",
    prompt: "Explain why a per-unit tax reduces quantity traded and creates deadweight loss in a competitive market.",
    rubric: [
      { label: "Explains tax creates a wedge between buyer price and seller price.", points: 2, keywords: [["wedge"], ["buyer", "seller"], ["price paid", "price received"]] },
      { label: "Explains quantity traded falls.", points: 1, keywords: [["quantity", "falls"], ["quantity traded", "decrease"]] },
      { label: "Connects lost trades to MB greater than MC.", points: 2, keywords: [["mb", "mc"], ["benefit", "cost"], ["mutually beneficial"]] },
      { label: "Defines deadweight loss as lost social surplus.", points: 2, keywords: [["deadweight"], ["social surplus"], ["welfare loss"]] },
      { label: "Mentions elasticity affects size of deadweight loss.", points: 1, keywords: [["elasticity"], ["elastic"]] },
    ],
    modelAnswer: "A per-unit tax drives a wedge between the price buyers pay and the price sellers receive. This reduces the quantity traded below the efficient competitive quantity. Some units for which marginal benefit exceeds marginal cost are no longer exchanged, so consumer and producer surplus are lost without becoming tax revenue. That lost social surplus is deadweight loss, and it is larger when supply or demand is more elastic.",
  },
  {
    id: "l1-ceteris-paribus",
    type: "short-answer",
    topic: "Economic foundations",
    source: "Lecture 1",
    title: "Ceteris paribus",
    prompt: "Why do economists use the ceteris paribus assumption?",
    rubric: [
      { label: "Explains that other factors are held constant.", points: 2, keywords: [["other", "constant"], ["remaining", "unchanged"], ["held", "constant"]] },
      { label: "Links the assumption to isolating one causal effect.", points: 2, keywords: [["isolate"], ["one variable"], ["causal"], ["effect"]] },
    ],
    modelAnswer: "Ceteris paribus means other things remain unchanged. Economists use it to isolate how a change in one variable affects behaviour or outcomes without other variables moving at the same time.",
  },
  {
    id: "l2-budget-line",
    type: "short-answer",
    topic: "PPF and trade",
    source: "Lecture 2",
    title: "Budget line",
    prompt: "What does a consumer budget line show?",
    rubric: [
      { label: "Mentions affordable combinations of goods.", points: 2, keywords: [["affordable", "combinations"], ["bundles", "afford"]] },
      { label: "Links the line to income and prices.", points: 2, keywords: [["income", "prices"], ["budget", "price"]] },
      { label: "Recognises the slope as an opportunity cost or relative price.", points: 1, keywords: [["slope"], ["relative price"], ["opportunity cost"]] },
    ],
    modelAnswer: "A budget line shows the combinations of two goods a consumer can afford with a given income and prices. Its slope reflects the relative price, or the opportunity cost of one good in terms of the other.",
  },
  {
    id: "l3-supply-shift-mcq",
    type: "multiple-choice",
    topic: "Demand and supply",
    source: "Lecture 3",
    title: "Supply decrease",
    prompt: "If a drought reduces the supply of milk, what happens to equilibrium price and quantity, all else equal?",
    options: ["Price rises and quantity falls", "Price falls and quantity rises", "Both price and quantity rise", "Both price and quantity fall"],
    answer: 0,
    explanation: "A decrease in supply shifts supply left. Equilibrium price rises and equilibrium quantity falls.",
  },
  {
    id: "l4-elasticity-determinants",
    type: "long-answer",
    topic: "Elasticity and policy",
    source: "Lecture 4",
    title: "Determinants of elasticity",
    prompt: "Explain three factors that make demand more or less price elastic.",
    rubric: [
      { label: "Discusses availability of close substitutes.", points: 2, keywords: [["substitutes"], ["close substitute"]] },
      { label: "Discusses budget share.", points: 2, keywords: [["budget share"], ["income"], ["spend"]] },
      { label: "Discusses time horizon.", points: 2, keywords: [["time"], ["long run"], ["short run"]] },
      { label: "Discusses necessity versus luxury.", points: 1, keywords: [["necessity"], ["luxury"]] },
    ],
    modelAnswer: "Demand is more elastic when there are close substitutes, when the good takes a large share of the budget, when consumers have more time to adjust, and when the good is a luxury rather than a necessity.",
  },
  {
    id: "l4-price-floor-mcq",
    type: "multiple-choice",
    topic: "Elasticity and policy",
    source: "Lecture 4",
    title: "Binding price floor",
    prompt: "A binding minimum wage is an example of a price floor. What does it tend to create in a labour market model?",
    options: ["A surplus of labour", "A shortage of labour", "No change because all price floors bind", "A rightward shift of labour demand"],
    answer: 0,
    explanation: "A binding price floor is above equilibrium. In a labour market model, quantity of labour supplied exceeds quantity demanded, creating a surplus of labour.",
  },
  {
    id: "l5-cash-kind",
    type: "long-answer",
    topic: "Consumer choice",
    source: "Lecture 5",
    title: "Cash versus in-kind transfer",
    prompt: "Why might a cash transfer give a consumer at least as much utility as an equal-value in-kind transfer?",
    rubric: [
      { label: "Explains cash expands choice or is flexible.", points: 2, keywords: [["cash", "choice"], ["cash", "flexible"], ["more options"]] },
      { label: "Explains in-kind transfer restricts the consumption bundle.", points: 2, keywords: [["in-kind", "restrict"], ["limited"], ["constraint"]] },
      { label: "Connects the answer to utility maximisation.", points: 2, keywords: [["utility"], ["best affordable"], ["maximise"]] },
    ],
    modelAnswer: "Cash can be spent on any bundle, so it lets the consumer choose the utility-maximising option from a larger feasible set. An in-kind transfer may force consumption of a particular good, which can leave the consumer no better than cash and sometimes worse if it is not what they would have chosen.",
  },
  {
    id: "l6-afc-avc",
    type: "short-answer",
    topic: "Production and costs",
    source: "Lecture 6",
    title: "AFC and AVC",
    prompt: "As output increases, why does the gap between ATC and AVC get smaller?",
    rubric: [
      { label: "Identifies the gap as AFC.", points: 2, keywords: [["afc"], ["average fixed cost"], ["fixed cost"]] },
      { label: "Explains fixed cost is spread over more output.", points: 2, keywords: [["spread"], ["more output"], ["larger output"]] },
      { label: "Concludes AFC falls as output rises.", points: 1, keywords: [["afc", "falls"], ["average fixed cost", "falls"]] },
    ],
    modelAnswer: "ATC equals AVC plus AFC. As output rises, the same fixed cost is spread over more units, so AFC falls and the vertical gap between ATC and AVC becomes smaller.",
  },
  {
    id: "l6-economies-scale-mcq",
    type: "multiple-choice",
    topic: "Production and costs",
    source: "Lecture 6",
    title: "Economies of scale",
    prompt: "Economies of scale occur when:",
    options: ["Long-run average cost falls as output expands", "Marginal cost is always above average cost", "Fixed cost rises with output", "All inputs are fixed"],
    answer: 0,
    explanation: "Economies of scale mean larger plant size or output lowers long-run average cost.",
  },
  {
    id: "l7-backward-induction",
    type: "short-answer",
    topic: "Game theory",
    source: "Lecture 7",
    title: "Backward induction",
    prompt: "How do you solve a sequential game using backward induction?",
    rubric: [
      { label: "Starts at the final decision nodes.", points: 2, keywords: [["end"], ["final"], ["last decision"]] },
      { label: "Chooses the optimal action for the player at each node.", points: 2, keywords: [["optimal"], ["best action"], ["best response"]] },
      { label: "Works backward to the first move.", points: 1, keywords: [["backward"], ["rollback"], ["first move"]] },
    ],
    modelAnswer: "Backward induction solves a sequential game by starting at the final decision nodes, choosing the best action for the player who moves there, and then rolling those choices back step by step to identify the first move and the subgame-perfect outcome.",
  },
  {
    id: "l7-multiple-nash-mcq",
    type: "multiple-choice",
    topic: "Game theory",
    source: "Lecture 7",
    title: "Multiple Nash equilibria",
    prompt: "Which game from the lecture is used as an example with more than one Nash equilibrium?",
    options: ["Battle of the Sexes", "A perfectly competitive market", "A PPF model", "A natural monopoly"],
    answer: 0,
    explanation: "Battle of the Sexes is a coordination game with two possible Nash equilibria.",
  },
  {
    id: "l8-entry-exit",
    type: "long-answer",
    topic: "Perfect competition",
    source: "Lecture 8",
    title: "Long-run entry and exit",
    prompt: "Explain how entry and exit move a perfectly competitive industry to long-run equilibrium.",
    rubric: [
      { label: "Positive economic profit attracts entry.", points: 2, keywords: [["profit", "entry"], ["positive", "enter"]] },
      { label: "Losses cause exit.", points: 2, keywords: [["loss"], ["exit"], ["leave"]] },
      { label: "Entry shifts market supply right and lowers price.", points: 1, keywords: [["supply", "right"], ["price", "fall"]] },
      { label: "Long-run equilibrium has zero economic profit.", points: 2, keywords: [["zero economic profit"], ["normal profit"]] },
      { label: "Mentions P equals minimum LRAC.", points: 1, keywords: [["minimum lrac"], ["min lrac"], ["minimum average cost"]] },
    ],
    modelAnswer: "If firms earn positive economic profit, new firms enter, shifting market supply right and pushing price down. If firms make losses, firms exit, shifting supply left and raising price. Long-run equilibrium occurs when there is no incentive for entry or exit, so firms earn zero economic profit and price equals minimum LRAC.",
  },
  {
    id: "l9-price-discrimination",
    type: "short-answer",
    topic: "Monopoly",
    source: "Lecture 9",
    title: "Price discrimination",
    prompt: "What is price discrimination, and what condition must a firm usually have to practise it?",
    rubric: [
      { label: "Defines charging different prices to different consumers.", points: 2, keywords: [["different prices"], ["different consumers"], ["same good"]] },
      { label: "Mentions market power.", points: 1, keywords: [["market power"], ["price maker"], ["monopoly"]] },
      { label: "Mentions ability to separate markets or prevent resale.", points: 2, keywords: [["separate"], ["resale"], ["segment"]] },
    ],
    modelAnswer: "Price discrimination means charging different consumers different prices for the same good when the difference is not based on cost. The firm needs market power and some ability to separate consumers or prevent resale.",
  },
  {
    id: "l9-regulation-natural-monopoly",
    type: "long-answer",
    topic: "Monopoly",
    source: "Lecture 9",
    title: "Natural monopoly regulation",
    prompt: "Why can marginal-cost pricing be difficult for a natural monopoly, and why might average-cost pricing be used instead?",
    rubric: [
      { label: "Explains natural monopoly has economies of scale or falling AC.", points: 2, keywords: [["economies of scale"], ["falling average cost"], ["downward sloping"]] },
      { label: "Explains marginal-cost pricing may set price below average cost.", points: 2, keywords: [["p", "ac"], ["below average cost"], ["loss"]] },
      { label: "Explains average-cost pricing allows normal profit or cost recovery.", points: 2, keywords: [["average cost pricing"], ["normal profit"], ["cover cost"]] },
      { label: "Mentions deadweight loss may be reduced but not eliminated.", points: 1, keywords: [["deadweight"], ["not eliminated"], ["minimised"]] },
    ],
    modelAnswer: "A natural monopoly often has falling average cost over the relevant output range. Marginal-cost pricing can force price below average cost, creating losses unless the firm is subsidised. Average-cost pricing lets the firm cover costs and earn normal profit, but it usually does not fully eliminate deadweight loss.",
  },
  {
    id: "l10-concentration-ratio",
    type: "short-answer",
    topic: "Imperfect competition",
    source: "Lecture 10",
    title: "Four-firm concentration ratio",
    prompt: "What does the four-firm concentration ratio measure?",
    rubric: [
      { label: "Mentions the four largest firms.", points: 2, keywords: [["four", "largest"], ["4", "largest"]] },
      { label: "Mentions proportion/share of industry revenue or sales.", points: 2, keywords: [["industry revenue"], ["market share"], ["sales"]] },
      { label: "Connects high concentration to less competition or oligopoly.", points: 1, keywords: [["oligopoly"], ["less competition"], ["concentrated"]] },
    ],
    modelAnswer: "The four-firm concentration ratio is the proportion of industry sales or revenue accounted for by the four largest firms. A higher ratio indicates a more concentrated and less competitive market.",
  },
  {
    id: "l10-kinked-demand",
    type: "short-answer",
    topic: "Imperfect competition",
    source: "Lecture 10",
    title: "Kinked demand",
    prompt: "Why can oligopoly prices be rigid in the kinked demand curve model?",
    rubric: [
      { label: "Rivals may not match price increases.", points: 2, keywords: [["not match", "price increase"], ["price increases", "lose customers"]] },
      { label: "Rivals may match price cuts.", points: 2, keywords: [["match", "price cuts"], ["price cuts", "match"]] },
      { label: "Explains this makes changing price unattractive.", points: 1, keywords: [["rigid"], ["sticky"], ["not change"]] },
    ],
    modelAnswer: "A firm fears that rivals will not match price increases, so it would lose many customers, but rivals will match price cuts, so cutting price gains little. This makes the current price relatively rigid.",
  },
  {
    id: "l11-policy-solutions",
    type: "long-answer",
    topic: "Externalities",
    source: "Lecture 11",
    title: "Internalising externalities",
    prompt: "Explain what it means to internalise a negative externality and give two policy approaches.",
    rubric: [
      { label: "Defines internalising as making decision-makers face the external cost.", points: 2, keywords: [["external cost"], ["face"], ["internalise"], ["internalize"]] },
      { label: "Mentions tax/Pigouvian tax.", points: 2, keywords: [["tax"], ["pigouvian"]] },
      { label: "Mentions regulation, permits, property rights or bargaining.", points: 2, keywords: [["regulation"], ["permit"], ["property rights"], ["bargaining"]] },
      { label: "Links policy to reducing output toward efficient quantity.", points: 1, keywords: [["efficient quantity"], ["reduce output"], ["less output"]] },
    ],
    modelAnswer: "Internalising a negative externality means making producers or consumers take the external cost into account. A Pigouvian tax can raise private cost toward social cost. Regulation, tradable permits, property rights or bargaining can also reduce output or pollution toward the efficient level.",
  },
  {
    id: "l12-good-types-mcq",
    type: "multiple-choice",
    topic: "Public goods",
    source: "Lecture 12",
    title: "Good classification",
    prompt: "A toll road with little congestion is best classified as:",
    options: ["Private good", "Public good", "Club/toll good", "Common resource"],
    answer: 2,
    explanation: "A toll road is excludable because users can be charged, and when uncongested it is largely non-rival, making it a club/toll good.",
  },
  {
    id: "l12-public-good-demand",
    type: "short-answer",
    topic: "Public goods",
    source: "Lecture 12",
    title: "Public good demand",
    prompt: "Why do we vertically sum individual marginal benefit curves for a public good?",
    rubric: [
      { label: "Mentions public goods are non-rival.", points: 2, keywords: [["non-rival"], ["non rival"]] },
      { label: "Explains everyone consumes the same unit.", points: 2, keywords: [["same unit"], ["same quantity"], ["all consume"]] },
      { label: "Explains social MB is the sum of each person's MB for each quantity.", points: 2, keywords: [["sum"], ["marginal benefit"], ["vertical"]] },
    ],
    modelAnswer: "Because a public good is non-rival, each unit is consumed by everyone at the same time. For each quantity, society's marginal benefit is the sum of each person's marginal benefit for that same unit, so we vertically sum individual MB curves.",
  },
  {
    id: "mix-market-power-efficiency",
    type: "long-answer",
    topic: "Monopoly",
    source: "Lectures 8 and 9",
    title: "Competition versus monopoly",
    prompt: "Compare the efficiency of perfect competition and monopoly using output, price and surplus.",
    rubric: [
      { label: "States perfect competition produces where P/MB equals MC.", points: 2, keywords: [["p", "mc"], ["mb", "mc"], ["competitive"]] },
      { label: "States monopoly restricts output where MR equals MC.", points: 2, keywords: [["mr", "mc"], ["restricts output"], ["monopoly"]] },
      { label: "Explains monopoly price is higher and quantity lower.", points: 2, keywords: [["higher price"], ["lower quantity"], ["p", "higher"]] },
      { label: "Explains monopoly creates deadweight loss or lower social surplus.", points: 2, keywords: [["deadweight"], ["social surplus"], ["welfare loss"]] },
    ],
    modelAnswer: "Perfect competition produces the efficient quantity where price, marginal benefit and marginal cost align, maximising social surplus. A monopolist chooses quantity where MR = MC and then charges the demand price, which is usually higher and at a lower output. The missing mutually beneficial trades create deadweight loss and reduce social surplus.",
  },
];
